const ranks=['Rookie','Club Player','Shooter','Competitor','Advanced','Expert','Master','Elite','Pro','Champion'];
const skillNames=['Shot Making','Cue-Ball Control','Position Play','Banks','Kicks','Safeties','Pattern Play'];
const drills=[
{id:'straight1',name:'Straight Shot I',skill:'Shot Making',desc:'Pocket 8 of 10 straight shots.',need:8,attempts:10,balls:[['cue',24,72],['1',50,50]],target:[82,18],tip:'Center ball • medium speed',instr:'Place the object ball near center table and cue ball on the diagonal shown. Pocket the object ball in the marked corner. Reset exactly after every attempt.'},
{id:'stop1',name:'Stop Shot I',skill:'Cue-Ball Control',desc:'Stop inside the target zone 7 of 10.',need:7,attempts:10,balls:[['cue',23,70],['2',50,50]],zone:[49,49],target:[82,18],tip:'Center-ball stun • firm-medium',instr:'Pocket the 2 and make the cue ball stop inside the blue circle. Count success only when the full cue ball finishes inside the zone.'},
{id:'follow1',name:'Follow Position I',skill:'Position Play',desc:'Reach the follow zone 7 of 10.',need:7,attempts:10,balls:[['cue',20,68],['3',45,50]],zone:[66,33],target:[82,18],tip:'½–1 tip above center • medium',instr:'Pocket the 3 and follow forward into the blue position zone.'},
{id:'draw1',name:'Draw Position I',skill:'Cue-Ball Control',desc:'Draw into the target zone 7 of 10.',need:7,attempts:10,balls:[['cue',35,66],['4',55,47]],zone:[20,78],target:[82,18],tip:'1 tip below center • smooth acceleration',instr:'Pocket the 4 and draw the cue ball back into the blue target zone.'},
{id:'bank1',name:'Cross-Side Banks',skill:'Banks',desc:'Make 6 of 10 cross-side banks.',need:6,attempts:10,balls:[['cue',26,72],['5',54,50]],target:[50,3],tip:'Center ball • controlled speed',instr:'Bank the 5 cross-side into the marked side pocket. Use the same setup for all ten attempts.'},
{id:'kick1',name:'One-Rail Kick Contact',skill:'Kicks',desc:'Make legal contact 7 of 10 times.',need:7,attempts:10,balls:[['cue',20,70],['6',72,26]],target:[50,3],tip:'Use the rail diamond system',instr:'Kick one rail into the 6. A legal first contact counts as success; pocketing is not required.'}
];
const defaults={results:{},xp:0,ghostMatches:[],skills:Object.fromEntries(skillNames.map(x=>[x,35]))};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('poolIQStateV2')||'{}')); state.results=state.results||{}; state.ghostMatches=state.ghostMatches||[]; state.skills=Object.assign({},defaults.skills,state.skills||{});
let activeDrill=null,attemptLog=[],ghostSession=null;
function save(){localStorage.setItem('poolIQStateV2',JSON.stringify(state));render()}
function passedCount(){return drills.filter(d=>state.results[d.id]?.passed).length}
function currentRank(){let g=state.ghostMatches.filter(m=>m.won).length;return Math.min(9,Math.floor(passedCount()/2)+Math.floor(g/3))}
function tableHTML(d){return `<div class='miniTable'><div class='pocket tl'></div><div class='pocket tm'></div><div class='pocket tr'></div><div class='pocket bl'></div><div class='pocket bm'></div><div class='pocket br'></div>${d.zone?`<div class='targetZone' style='left:${d.zone[0]}%;top:${d.zone[1]}%'></div>`:''}${d.balls.map(b=>`<div class='vball ${b[0]==='cue'?'vcue':''}' style='left:${b[1]}%;top:${b[2]}%'>${b[0]==='cue'?'':b[0]}</div>`).join('')}<div class='aimPocket' style='left:${d.target[0]}%;top:${d.target[1]}%'></div></div>`}
function renderSkills(id){document.getElementById(id).innerHTML=skillNames.map(n=>`<div class='skill'><span>${n}</span><div class='meter'><i style='width:${state.skills[n]}%'></i></div><b>${state.skills[n]}</b></div>`).join('')}
function openDrill(id){activeDrill=drills.find(d=>d.id===id);attemptLog=[];document.getElementById('drillModal').classList.add('show');renderDrillModal()}
function renderDrillModal(){let d=activeDrill,old=state.results[d.id];document.getElementById('drillModalBody').innerHTML=`<button class='close' onclick='closeDrill()'>×</button><span class='eyebrow'>${d.skill}</span><h1>${d.name}</h1>${tableHTML(d)}<p class='instructions'>${d.instr}</p><div class='tip'>🎯 ${d.tip}</div><div class='scoreHead'><b>Attempt ${Math.min(attemptLog.length+1,d.attempts)} / ${d.attempts}</b><span>Pass: ${d.need}/${d.attempts}</span></div><div class='attemptDots'>${Array.from({length:d.attempts},(_,i)=>`<i class='${attemptLog[i]===1?'hit':attemptLog[i]===0?'miss':''}'>${i+1}</i>`).join('')}</div>${attemptLog.length<d.attempts?`<div class='scoreBtns'><button class='missBtn' onclick='recordAttempt(0)'>✕ Miss</button><button class='hitBtn' onclick='recordAttempt(1)'>✓ Success</button></div>`:`<button class='saveScore' onclick='finishDrill()'>Save ${attemptLog.reduce((a,b)=>a+b,0)}/${d.attempts} Result</button>`}${old?`<p class='best'>Best saved: <b>${old.best}/${d.attempts}</b> • ${old.passed?'PASSED':'Not passed yet'}</p>`:''}`}
function recordAttempt(v){attemptLog.push(v);renderDrillModal()}
function finishDrill(){let d=activeDrill,score=attemptLog.reduce((a,b)=>a+b,0),old=state.results[d.id]||{best:0,tries:0,passed:false};let firstPass=!old.passed&&score>=d.need;state.results[d.id]={best:Math.max(old.best,score),tries:old.tries+1,passed:old.passed||score>=d.need,last:score};if(firstPass){state.xp+=100;state.skills[d.skill]=Math.min(99,state.skills[d.skill]+7)} save();renderDrillModal()}
function closeDrill(){document.getElementById('drillModal').classList.remove('show');activeDrill=null}
function startGhost(n){let maxUnlocked=3+Math.floor(state.ghostMatches.filter(m=>m.won).length/2);if(n>maxUnlocked)return;ghostSession={balls:n,you:0,ghost:0,race:5,log:[]};document.getElementById('ghostModal').classList.add('show');renderGhost()}
function renderGhost(){let g=ghostSession;document.getElementById('ghostModalBody').innerHTML=`<button class='close' onclick='closeGhost()'>×</button><span class='eyebrow'>${g.balls}-BALL GHOST</span><h1>Race to ${g.race}</h1><div class='ghostScore'><div><b>${g.you}</b><span>YOU</span></div><em>—</em><div><b>${g.ghost}</b><span>GHOST</span></div></div><p class='instructions'>Rack ${g.balls} balls. Break, take ball in hand, and try to run out. If you clear the table, you win the rack. A miss, foul, or failed runout gives the rack to the Ghost.</p><div class='racklog'>${g.log.map((x,i)=>`<span class='${x==='W'?'win':'loss'}'>R${i+1} ${x}</span>`).join('')}</div>${g.you<g.race&&g.ghost<g.race?`<div class='scoreBtns'><button class='missBtn' onclick="ghostRack('L')">Ghost Wins Rack</button><button class='hitBtn' onclick="ghostRack('W')">I Ran Out</button></div>`:`<button class='saveScore' onclick='saveGhost()'>Save Match — ${g.you>g.ghost?'YOU WIN':'GHOST WINS'} ${g.you}-${g.ghost}</button>`}`}
function ghostRack(x){ghostSession.log.push(x);x==='W'?ghostSession.you++:ghostSession.ghost++;renderGhost()}
function saveGhost(){let g=ghostSession,won=g.you>g.ghost;state.ghostMatches.push({balls:g.balls,you:g.you,ghost:g.ghost,won,date:new Date().toISOString()});if(won){state.xp+=150;state.skills['Pattern Play']=Math.min(99,state.skills['Pattern Play']+3)}save();renderGhost()}
function closeGhost(){document.getElementById('ghostModal').classList.remove('show');ghostSession=null}
function render(){let r=currentRank(),pc=passedCount(),gw=state.ghostMatches.filter(m=>m.won).length,progress=Math.min(100,((pc%2)/2)*70+(gw%3)/3*30);rankName.textContent=ranks[r].toUpperCase();rankNum.textContent=r+1;rankBar.style.width=progress+'%';rankPct.textContent=Math.round(progress)+'%';nextRank.textContent=r<9?'Next: '+ranks[r+1]:'Max Rank';
missions.innerHTML=drills.filter(d=>!state.results[d.id]?.passed).slice(0,3).map(card).join('')||`<div class='card mission'><h3>Training set cleared</h3><p>You've passed the available v2 drills.</p></div>`;drillList.innerHTML=drills.map(card).join('');renderSkills('skills');renderSkills('statsSkills');
ranksEl.innerHTML=ranks.map((n,i)=>`<div class='rank card ${i>r?'locked':i===r?'current':''}'><div class='num'>${i+1}</div><div><h3>${n}</h3><p>${i===0?'Fundamentals':i<4?'Control, patterns & consistency':i<7?'Advanced position, defense & runouts':'High-pressure mastery'}</p></div><div class='status'>${i<r?'✓ PASSED':i===r?'● CURRENT':'🔒 LOCKED'}</div></div>`).join('');
let maxUnlocked=3+Math.floor(gw/2);ghostLevels.innerHTML=Array.from({length:7},(_,j)=>j+3).map(n=>`<div class='rank card ${n>maxUnlocked?'locked':''}'><div class='num'>${n}</div><div><h3>${n}-Ball Ghost</h3><p>Race to 5 • ball in hand after break • every rack is scored.</p></div><button ${n>maxUnlocked?'disabled':''} onclick='startGhost(${n})'>${n>maxUnlocked?'🔒':'Play Match'}</button></div>`).join('');
xp.textContent=state.xp;completed.textContent=pc;ghostWins.textContent=gw;let hist=state.ghostMatches.slice().reverse().slice(0,6);ghostHistory.innerHTML=hist.length?hist.map(m=>`<div class='historyRow'><span>${m.balls}-Ball Ghost</span><b class='${m.won?'green':'red'}'>${m.won?'WIN':'LOSS'} ${m.you}-${m.ghost}</b></div>`).join(''):`<p class='muted'>No Ghost matches recorded yet.</p>`}
function card(d){let x=state.results[d.id];return `<div class='drill card'>${tableHTML(d)}<span class='tag'>${d.skill}</span><h3>${d.name}</h3><p>${d.desc}</p>${x?`<div class='result ${x.passed?'green':'red'}'>Best ${x.best}/${d.attempts} • ${x.passed?'PASSED':'KEEP TRAINING'}</div>`:''}<button onclick="openDrill('${d.id}')">${x?.passed?'Practice Again':'Start Drill'}</button></div>`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page,nav button').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');b.classList.add('active');scrollTo(0,0)});resetBtn.onclick=()=>{if(confirm('Reset all Pool IQ v2 progress?')){localStorage.removeItem('poolIQStateV2');location.reload()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
