const ranks=['Rookie','Club Player','Shooter','Competitor','Advanced','Expert','Master','Elite','Pro','Champion'];
const skillNames=['Shot Making','Cue-Ball Control','Position Play','Banks','Kicks','Safeties','Pattern Play'];
const drills=[
['Straight Shot I','Shot Making','Pocket 8 of 10 straight shots','🎯',8],['Stop Shot I','Cue-Ball Control','Stop inside target zone 7 of 10','⏹',7],['Follow Position I','Position Play','Reach the target zone 7 of 10','↗',7],['Draw Position I','Cue-Ball Control','Draw into target zone 7 of 10','↙',7],['3-Ball Runout','Pattern Play','Complete 4 of 5 layouts','③',4],['Safety Lock','Safeties','Win 7 of 10 safety situations','◈',7],['Cross-Side Banks','Banks','Make 6 of 10 banks','◇',6],['Two-Rail Kick','Kicks','Contact legal target 7 of 10','⌁',7],['Combo Control','Shot Making','Make 6 of 10 combinations','⑧',6]];
let state=JSON.parse(localStorage.getItem('poolIQState')||'null')||{passed:[],xp:0,ghostWins:0,skills:Object.fromEntries(skillNames.map(x=>[x,35]))};
function save(){localStorage.setItem('poolIQState',JSON.stringify(state));render()}
function currentRank(){return Math.min(9,Math.floor(state.passed.length/2)+Math.floor(state.ghostWins/3))}
function renderSkills(id){document.getElementById(id).innerHTML=skillNames.map(n=>`<div class='skill'><span>${n}</span><div class='meter'><i style='width:${state.skills[n]}%'></i></div><b>${state.skills[n]}</b></div>`).join('')}
function passDrill(i){if(!state.passed.includes(i)){state.passed.push(i);state.xp+=100;let s=drills[i][1];state.skills[s]=Math.min(99,state.skills[s]+7);save()}}
function ghostWin(level){if(level<=Math.floor(state.ghostWins/2)+3){state.ghostWins++;state.xp+=150;state.skills['Pattern Play']=Math.min(99,state.skills['Pattern Play']+3);save()}}
function render(){let r=currentRank(),progress=Math.min(100,((state.passed.length%2)/2)*100+(state.ghostWins%3)*12);document.getElementById('rankName').textContent=ranks[r].toUpperCase();document.getElementById('rankNum').textContent=r+1;document.getElementById('rankBar').style.width=progress+'%';document.getElementById('rankPct').textContent=progress+'%';document.getElementById('nextRank').textContent=r<9?'Next: '+ranks[r+1]:'Max Rank';
let todo=drills.map((d,i)=>({d,i})).filter(x=>!state.passed.includes(x.i)).slice(0,3);document.getElementById('missions').innerHTML=todo.length?todo.map(x=>card(x.d,x.i,'mission')).join(''):`<div class='card mission'><h3>Daily training cleared</h3><p>You've passed every prototype drill.</p></div>`;
document.getElementById('drillList').innerHTML=drills.map((d,i)=>card(d,i,'drill')).join('');renderSkills('skills');renderSkills('statsSkills');
document.getElementById('ranks').innerHTML=ranks.map((n,i)=>`<div class='rank card ${i>r?'locked':i===r?'current':''}'><div class='num'>${i+1}</div><div><h3>${n}</h3><p>${i===0?'Fundamentals':i<4?'Control, patterns & consistency':i<7?'Advanced position, defense & runouts':'High-pressure mastery & complete-game tests'}</p></div><div class='status'>${i<r?'✓ PASSED':i===r?'● CURRENT':'🔒 LOCKED'}</div></div>`).join('');
document.getElementById('ghostLevels').innerHTML=Array.from({length:7},(_,j)=>j+3).map(n=>{let unlocked=n<=Math.floor(state.ghostWins/2)+3;return `<div class='rank card ${unlocked?'':'locked'}'><div class='num'>${n}</div><div><h3>${n}-Ball Ghost</h3><p>Ball in hand after the break. Run the table to score a win.</p></div><button ${unlocked?'':'disabled'} onclick='ghostWin(${n})'>${unlocked?'Record Win':'🔒'}</button></div>`}).join('');document.getElementById('xp').textContent=state.xp;document.getElementById('completed').textContent=state.passed.length;document.getElementById('ghostWins').textContent=state.ghostWins}
function card(d,i,cls){let done=state.passed.includes(i);return `<div class='${cls} card'><div class='icon'>${d[3]}</div><span class='tag'>${d[1]}</span><h3>${d[0]}</h3><p>${d[2]}</p><button class='${done?'done':''}' onclick='passDrill(${i})'>${done?'✓ Passed':'Start / Pass Demo'}</button></div>`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page,nav button').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');b.classList.add('active');scrollTo(0,0)});document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all Pool IQ demo progress?')){localStorage.removeItem('poolIQState');location.reload()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
